version: '3.8'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql_achat
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  achat-app:
    image: oumardiaw/achat:1.0-SNAPSHOT
    container_name: achat_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data: